### ISSUE TITLE
Top selection sometimes gets cut off on mobile

### ISSUE THREAD

**Issue by SHTDJ** [dustinengle/blockex#11]
This issue is easy to recreate by scrolling down after you reached the bottom of the page already. This sometimes happens for no apparant reason aswell
![screenshot_2018-03-10-02-54-29](https://user-images.githubusercontent.com/36552562/37237055-c717b072-240e-11e8-9969-fdb47b82ce69.png)

**Comment by imprecation** [comment]
should be fixed with:
https://github.com/dustinengle/blockex/commit/eddeca582cf727f67712b125b6744793c28fff02#diff-d627080f480f213404b16c7b2b0f27d7
