### ISSUE TITLE
Homepage table title innacurate

### ISSUE THREAD

**Issue by KaneoHunter** [dustinengle/blockex#15]
The homepage table is titled "LATEST TRANSACTIONS" but shows latest blocks.

**Comment by dustinengle** [comment]
Thank you for the issue submission but the overview page does show the latest transactions.  If the block height is clicked it will load the block view and not the tx like clicking on the hash, is that what you are experiencing?

**Comment by KaneoHunter** [comment]
Yes, it's functioning fine. I just felt "latest blocks" was a more accurate description.
